name: Price Tracker

on:
  push:
    branches: [main]
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 test.py
      - name: setup git config
        run:  |
          git --global config user.name ${{secrets.userName}}
          git --global config user.email ${{secrets.userEmail}}
      - name: commit changes
        run:  |
          git add -A
          git commit -m "new file addition"
          git push origin main
