name: Flat

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          token : ${{secrets.pat_token}}
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url : https://www.amazon.in/Crucial-DDR4-Laptop-Memory-CT8G4SFRA266/dp/B08C56KXQJ/?_encoding=UTF8&pd_rd_w=Blo93&pf_rd_p=ee853eb9-cee5-4961-910b-2f169311a086&pf_rd_r=2TBHP2N9H2Y3MASS5EJE&pd_rd_r=b91f3d30-f91d-4514-9f8e-484d5d996679&pd_rd_wg=luNZp&ref_=pd_gw_ci_mcx_mr_hp_atf_m&th=1
          downloaded_filename: ./data.txt
